name: CI & Release

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  # Build, Lint, Test, and produce a DMG artifact on main pushes
  build:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode 15
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          brew install node swiftlint swiftformat
          brew install create-dmg

      - name: Run SwiftLint
        run: swiftlint lint --strict

      - name: Check SwiftFormat
        run: swiftformat . --lint

      - name: Build Debug
        run: |
          xcodebuild \
            -scheme "BeeAway" \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build | xcpretty

      - name: Run Unit & UI Tests
        run: |
          xcodebuild \
            -scheme "BeeAway" \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            test | xcpretty

      # On pushes to main, also build a DMG artifact
      - name: Build Release for DMG artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          SETTINGS=$(xcodebuild \
            -scheme "BeeAway" \
            -configuration Release \
            -destination 'platform=macOS' \
            -showBuildSettings)

          # Extract the CONFIGURATION_BUILD_DIR
          BUILD_DIR=$(echo "$SETTINGS" \
            | awk -F'= ' '/BUILD_DIR/ { print $2 }' \
            | head -1)
          
          echo "Products are in: $BUILD_DIR"
          
          xcodebuild \
            -scheme "BeeAway" \
            -configuration Release \
            -destination 'platform=macOS' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build | xcpretty
          mkdir -p dist
          cp -R "$BUILD_DIR/Release/BeeAway.app" dist/
          echo "Copied .app to dist/"
          
          create-dmg \
            --volname "BeeAway Installer" \
            --background "resources/dmg-background.png" \
            --icon "BeeAway.app" 120 120 \
            --app-drop-link 400 120 \
            --window-size 540 300 \
            dist/BeeAway-${{ github.run_id }}.dmg \
            dist/

      - name: Upload DMG Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: BeeAway-dmg-${{ github.run_id }}
          path: dist/BeeAway-${{ github.run_id }}.dmg
          retention-days: 7

  # Release on annotated v* tags
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: write
      actions: read
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install JavaScript dependencies
        run: npm install

      - name: Set up Git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CHANGELOG and bump version
        run: npm run release -- --release-as ${{ github.ref_name }} --no-push


      - name: Set up Xcode 15
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install create-dmg
        run: |
          brew install node
          brew install create-dmg

      - name: Build Release .app
        run: |
          xcodebuild \
            -scheme "BeeAway" \
            -configuration Release \
            -destination 'platform=macOS' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean build | xcpretty

      - name: Copy `.app` to staging
        run: |
          SETTINGS=$(xcodebuild \
              -scheme "BeeAway" \
              -configuration Release \
              -destination 'platform=macOS' \
              -showBuildSettings)

          # Extract the CONFIGURATION_BUILD_DIR
          BUILD_DIR=$(echo "$SETTINGS" \
            | awk -F'= ' '/BUILD_DIR/ { print $2 }' \
            | head -1)
          
          echo "Products are in: $BUILD_DIR"

          mkdir -p dist
          cp -R "$BUILD_DIR/Release/BeeAway.app" dist/

      - name: Create DMG
        run: |
          create-dmg \
            --volname "BeeAway Installer" \
            --background "resources/dmg-background.png" \
            --icon "BeeAway.app" 120 120 \
            --app-drop-link 400 120 \
            --window-size 540 300 \
            dist/BeeAway-${{ github.ref_name }}.dmg \
            dist/

      - name: Push changelog commit and tags
        run: |
          # always push HEAD into main branch
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish GitHub Release w/ DMG
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: BeeAway-${{ github.ref_name }}.dmg
          body_path: CHANGELOG.md
          files: dist/BeeAway-${{ github.ref_name }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute SHA256 of DMG
        id: compute-sha
        run: |
          VERSION=${GITHUB_REF_NAME}
          DMG="dist/BeeAway-${VERSION}.dmg"
          echo "Computing SHA256 for ${DMG}"
          shasum -a 256 "$DMG" | awk '{print $1}' > sha.txt
          SHA256=$(cat sha.txt)
          echo "sha256=$SHA256" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Compute bare version
        id: bare_version
        run: |
          # github.ref_name is "v0.0.1"
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"


      - name: Dispatch tap update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TAP_DISPATCH_TOKEN }}
          repository: ragarwalll/homebrew-tap
          event-type: bump-bee-away-cask
          client-payload: |
            {
              "version": "${{ steps.bare_version.outputs.version }}",
              "sha256": "${{ steps.compute-sha.outputs.sha256 }}",
              "cask_name": "bee-away"
            }