name: push-to-gh-pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GH-Pages using Minimalify
        uses: ragarwalll/deploy-with-minimalify@v1
        with:
          package-manager: npm
          node-version: '20'
          cache-deps: true
          precheck: true
          workdir: 'docs'
          branch: gh-pages
          config-file: './minimalify.config.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}